// React/lab1/src/Components/first/FirstComponent.js
import { Component } from "react";
import "./FirstComponent.css";

class FirstComponent extends Component {
  name = "";
  getData = (e) => {
    this.setState({ name: e.target.value });
  };

  resetName = (e) => {
    this.setState({ name: "" });
  };

  constructor() {
    super();
    this.state = {
      name: "",
    };
  }
  render() {
    return (
      <div class="container">
        <input
          type="text"
          placeholder="Enter Your name"
          value={this.state.name}
          onChange={this.getData}
        />
        <p>
          <span>Your Name is: </span> {this.state.name}
        </p>
        <button onClick={this.resetName}>Reset</button>
      </div>
    );
  }
}

export default FirstComponent;

// Angular/Day 2/lab/src/app/first/first.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-first',
  templateUrl: './first.component.html',
  styleUrls: ['./first.component.css'],
})
export class FirstComponent {
  inputVal = '';

  reset() {
    this.inputVal = '';
  }
}

<div class="container">
  <input type="text" [(ngModel)]="inputVal" placeholder="Enter Your name" />
  <p><span>Your Name is: </span> {{ inputVal }}</p>
  <button (click)="reset()">Reset</button>
</div>
